# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa4bda0112302aff1a9b098c37ad2713caf5d035036ea05054d338781ad980a79f047cacf804c567109064a9740c9ecb19fed6d442b6557114e9c554a3f50d87
  rome_key: ENV['rome']

test:
  secret_key_base: 2d4187976122597c25f4c3bbeaa5a5c8ce27ba79b9e22c2da8fd63a2167614103a81ba3e20ddfde612337cdb217dcc5e1f1c8f6deed77e3ae3699fb42ea4a78a
  rome_key: ENV['rome']

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rome_key: ENV['rome']