# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Destination.create(city: 'Milan', background_id: 'mxp-illust', code: 'MXP',
				   overview: "Milan is the second-most populous city in Italy, serves as the capital of Lombardy. The city proper has a population of about 1.3 million, while its urban area (the 5th-largest in the EU) comprises an estimated 5,264,000 people. The massive suburban sprawl that followed the post-war boom of the 1950s–1960s and the growth of a vast commuter belt suggest that socioeconomic linkages have expanded well beyond the boundaries of its administrative limits and its agglomeration, creating a polycentric metropolitan area of 7 to 10 million people, stretching over the provinces of Milan, Bergamo, Como, Lecco, Lodi, Monza and Brianza, Pavia, Varese and Novara. The Milan metropolitan region is part of the so-called Blue Banana, the area of Europe with the highest population and industrial density. In terms of GDP, Milan has the third largest economy among EU cities and the largest among European non-capital cities", 
				   culture: "Milan is home to many cultural institutions, museums and art galleries, that account for about a tenth of the national total of visitors and recepits. The Pinacoteca di Brera is one of Milan's most important art galleries. It contains one of the foremost collections of Italian painting, including masterpieces such as the Brera Madonna by Piero della Francesca. The Castello Sforzesco hosts numerous art collections and exhibitions, especially statues, ancient arms and furnitures, as well as the Pinacoteca del Castello Sforzesco, with an art collection including Michelangelo's last sculpture, the Rondanini Pietà, Andrea Mantegna's Trivulzio Madonna and Leonardo da Vinci's Codex Trivulzianus manuscript. The Castello complex also includes The Museum of Ancient Art, The Furniture Museum, The Museum of Musical Instruments and the Applied Arts Collection, The Egyptian and Prehistoric sections of the Archaeological Museum and the Achille Bertarelli Print Collection.", 
				   transportation: "Milan has an extensive internal transport network and is also an important transportation node in Italy, being one of the country's biggest hubs for air, rail and road networks. Internal public transport network includes the Metro, the Suburban Railway, the tram and bus network, as well as taxi, car and bike sharing services.", 
				   food: 'Like most cities in Italy, Milan has developed its own local culinary tradition, which, as it is typical for North Italian cuisines, uses more frequently rice than pasta, butter than vegetable oil and features almost no tomato or fish. Milanese traditional dishes includes cotoletta alla milanese, a breaded veal (pork and turkey can be used) cutlet pan-fried in butter (similar to Viennese "Wienerschnitzel"). Other typical dishes are cassoeula (stewed pork rib chops and sausage with Savoy cabbage), ossobuco (braised veal shank served with a condiment called gremolata), risotto alla milanese (with saffron and beef marrow), busecca (stewed tripe with beans), and brasato (stewed beef or pork with wine and potatoes). Season-related pastries include chiacchiere (flat fritters dusted with sugar) and tortelli (fried spherical cookies) for Carnival, colomba (glazed cake shaped as a dove) for Easter, pane dei morti (Deads Day bread, cookies aromatized with cinnamon) for All Souls Day and panettone for Christmas. The salame Milano, a salami with a very fine grain, is widespread throughout Italy. Renowned Milanese cheeses are gorgonzola (from the namesake village nearby), mascarpone, used in pastry-making, taleggio and quartirolo.', 
				   entertainment: 'Milan is a great city to walk around and see the sights and people.')
Destination.create(city: 'Tokyo', background_id: 'nrt-illust', code: 'NRT',
				   overview: "Tokyo, is one of the 47 prefectures of Japan,[6] and is both the capital and largest city of Japan. The Greater Tokyo Area is the most populous metropolitan area in the world. It is the seat of the Emperor of Japan and the Japanese government. Tokyo is in the Kantō region on the southeastern side of the main island Honshu and includes the Izu Islands and Ogasawara Islands. Formerly known as Edo, it has been the de facto seat of government since 1603 when Shogun Tokugawa Ieyasu made the city his headquarters. It officially became the capital after Emperor Meiji moved his seat to the city from the old capital of Kyoto in 1868; at that time Edo was renamed Tokyo. Tokyo Metropolis was formed in 1943 from the merger of the former Tokyo Prefecture (東京府 Tōkyō-fu) and the city of Tokyo (東京市 Tōkyō-shi).", 
				   culture: "Tokyo has many museums. In Ueno Park, there is the Tokyo National Museum, the country's largest museum and specializing in traditional Japanese art; the National Museum of Western Art and Ueno Zoo. Other museums include the National Museum of Emerging Science and Innovation in Odaiba; the Edo-Tokyo Museum in Sumida, across the Sumida River from the center of Tokyo; the Nezu Museum in Aoyama; and the National Diet Library, National Archives, and the National Museum of Modern Art, which are near the Imperial Palace.", 
				   transportation: "Tokyo, as the center of the Greater Tokyo Area, is Japan's largest domestic and international hub for rail, ground, and air transportation. Public transportation within Tokyo is dominated by an extensive network of clean and efficient trains and subways run by a variety of operators, with buses, monorails and trams playing a secondary feeder role.", 
				   food: "The sheer quantity, variety and quality of food in Tokyo will amaze you. Department stores have food halls, typically in the basement (called depachika), with food which surpasses top delicatessens in other world cities. Some basements of train stations have supermarkets with free taste testers. It's a great way to sample some of the strange dishes they have for free. Tokyo has a large number of restaurants, so see the main Japan guide for the types of food you will encounter and some popular chains. Menus are often posted outside, so you can check the prices. Some shops have the famous plastic food in their front windows. Don't hesitate to drag the waiting staff out to the front to point at what you want. Always carry cash. Many restaurants will not accept credit cards.", 
				   entertainment: "Tokyo has a vast array of sights, but the first items on the agenda of most visitors are the temples of Asakusa, the gardens of the Imperial Palace (in Chiyoda) and the Meiji Shrine (明治神宮, in Harajuku).")
Destination.create(city: 'New York', background_id: 'nyc-illust', code: 'NYC',
				   overview: "New York – often called New York City or the City of New York to distinguish it from the State of New York, of which it is a part – is the most populous city in the United States and the center of the New York metropolitan area, the premier gateway for legal immigration to the United States and one of the most populous urban agglomerations in the world. A global power city, New York exerts a significant impact upon commerce, finance, media, art, fashion, research, technology, education, and entertainment. Home to the headquarters of the United Nations, New York is an important center for international diplomacy and has been described as the cultural and financial capital of the world.", 
				   culture: "New York City has been described as the cultural capital of the world by the diplomatic consulates of Iceland and Latvia and by New York's Baruch College. A book containing a series of essays titled New York, culture capital of the world, 1940–1965 has also been published as showcased by the National Library of Australia.In describing New York, author Tom Wolfe said, 'Culture just seems to be in the air, like part of the weather.", 
				   transportation: "Most of NYC is laid out in a grid. By convention, Manhattan is spoken of as if it runs north to south (it's actually northeast to southwest), with streets running east and west and avenues running north and south. This makes it relatively easy and straightforward to find your way. Streets are numbered (except in downtown Manhattan) and the numbering rises as you go north. Most avenues are numbered from east to west (so First Ave is east of Second, etc.) below 59th St. Building numbering on avenues starts at the south end of the avenue and rises as you move north, while building numbering on streets starts at Fifth Ave (for the most part - see below) and increases as you go east or west crosstown.", 
				   food: "New York City's food culture includes a variety of international cuisines influenced by the city's immigrant history. Central European and Italian immigrants originally made the city famous for bagels, cheesecake, and New York-style pizza, while Chinese and other Asian restaurants, sandwich joints, trattorias, diners, and coffeehouses have become ubiquitous. Some 4,000 mobile food vendors licensed by the city, many immigrant-owned, have made Middle Eastern foods such as falafel and kebabs popular examples of modern New York street food. The city is also home to nearly one thousand of the finest and most diverse haute cuisine restaurants in the world, according to Michelin.The New York City Department of Health and Mental Hygiene assigns letter grades to the city's 24,000 restaurants based upon their inspection results.", 
				   entertainment: "New York's Broadway is famous for its many shows, especially musicals. You might want to visit TKTS online, which offers tickets for shows the same night at discounted prices, usually 50% off or visit BroadwayBox.com or NYTix.com, both community sites posting all recent Broadway discounts. TKTS has two offices, one at Times Square with lines often hours long, and a much faster one (sometimes minutes) at South Street Seaport (Corner of John St, just south of Brooklyn Bridge). Only cash is accepted at South Street. Show up at opening time for best selection. Tickets to most Broadway shows are also available from the Broadway Concierge and Ticket Center, inside the Times Square Visitor Center. They offer restaurant and hotel recommendations, parking help, and other services in addition to ticket sales, available in several languages.")
Destination.create(city: 'Prague', background_id: 'prg-illust', code: 'PRG',
				   overview: "Prague is the capital and largest city of the Czech Republic. It is the 15th largest city in the European Union. It is also the historical capital of Bohemia. Situated in the north-west of the country on the Vltava River, the city is home to about 1.24 million people, while its larger urban zone is estimated to have a population of nearly 2 million. The city has a temperate climate, with warm summers and chilly winters. The origin of the name Praha is rather associated with the word prah (that means a 'threshold'), which is a rapid on the river. Prague has the lowest unemployment rate in the European Union.", 
				   culture: "This magical city of bridges, cathedrals, gold-tipped towers and church domes, has been mirrored in the surface of the swan-filled Vltava River for more than ten centuries. Almost undamaged by WWII, Prague's medieval centre remains a wonderful mixture of cobbled lanes, walled courtyards, cathedrals and countless church spires all in the shadow of her majestic 9th century castle that looks eastward as the sun sets behind her. Prague is also a modern and vibrant city full of energy, music, cultural art, fine dining and special events catering to the independent traveller's thirst for adventure.", 
				   transportation: "The public transport infrastructure (PID, Pražská integrovaná doprava) consists of a heavily-used integrated transport system of Prague Metro (lines A, B, and C - its length is 65 km (40 mi) with 61 stations in total), Prague tram system, Prague buses, funiculars, and six ferries. Prague has one of the highest rates of public transport usage in the world,[citation needed] with 1.2 billion passenger journeys per year. Prague has about 130 bus lines (numbers 100-299) and 22 tram lines (numbers 1-26). There are also three funiculars, one on Petřín Hill, one on Mrázovka Hill and a third at the Zoo in Troja.", 
				   food: "Lunch is traditionally the main meal in Prague. Czech cuisine is typically based around pork or chicken with starchy side dishes such as dumplings, potatoes, or fries. Fish and beef is not as popular, though these days it is widely available. Popular Czech desserts include fruit dumplings (ovocné knedlíky), crêpes or ice cream. Most restaurants become very crowded during lunch and dinner, so consider making a reservation or eating earlier than the locals.", 
				   entertainment: "Since the fall of the Iron Curtain, Prague has become one of the world's most popular tourist destinations. Prague suffered considerably less damage during World War II than some other major cities in the region, allowing most of its historic architecture to stay true to form. It contains one of the world's most pristine and varied collections of architecture, from Romanesque, to Gothic, Renaissance, Baroque, Rococo, Neo-Renaissance, Neo-Gothic, Art Nouveau, Cubist, Neo-Classical and ultra-modern.")
Destination.create(city: 'San Francisco', background_id: 'sfo-illust', code: 'SFO',
				   overview: "San Francisco is a popular tourist destination,known for its cool summers, fog, steep rolling hills, eclectic mix of architecture, and landmarks including the Golden Gate Bridge, cable cars, the former Alcatraz Federal Penitentiary, and its Chinatown district. San Francisco is also the headquarters of five major banking institutions and various other companies such as Levi Strauss & Co., Gap Inc., Salesforce.com, Dropbox, Reddit, Square, Inc., Airbnb, Weebly, Pacific Gas and Electric Company, Yelp, Pinterest, Twitter, Uber, Mozilla, Wikimedia Foundation and Craigslist.", 
				   culture: "San Francisco is also characterized by its numerous culturally rich streetscapes featuring mixed-use neighborhoods anchored around central commercial corridors to which residents and visitors alike can walk. Because of these characteristics, San Francisco is ranked the second most walkable city in the U.S. by Walkscore.com. Many neighborhoods feature a mix of businesses, restaurants and venues that cater to both the daily needs of local residents while also serving many visitors and tourists. Some neighborhoods are dotted with boutiques, cafes and nightlife such as Union Street in Cow Hollow, 24th Street in Noe Valley, Valencia Street in the Mission, Grant St. in North Beach, and Irving Street in the Inner Sunset. This approach especially has influenced the continuing South of Market neighborhood redevelopment with businesses and neighborhood services rising alongside high-rise residences", 
				   transportation: "Transportation in the San Francisco Bay Area is reliant on a complex multimodal infrastructure consisting of roads, bridges, highways, rail, tunnels, airports, and bike and pedestrian paths. The development, maintenance, and operation of these different modes of transportation are overseen by various agencies, including the California Department of Transportation (Caltrans), the Association of Bay Area Governments, San Francisco Municipal Transportation Agency, and the Metropolitan Transportation Commission. These and other organizations collectively manage several interstate highways and state routes, two subway networks, two commuter rail agencies, eight trans-bay bridges, a ferry, local bus service, three international airports, and an extensive network of roads, tunnels, and bike paths. A 2011 Brookings Institution study ranked the San Francisco MSA and the San Jose MSA sixteenth and second, respectively, on transit coverage to job access. Another nationwide study, conducted by the University of Minnesota in 2014, ranked the San Francisco MSA second and San Jose MSA tenth.", 
				   food: "San Francisco is a sensual, epicurean city with a vast array of restaurants. In fact, San Francisco has more restaurants per capita than any major city in North America, with 1 restaurant for every 250 residents (in comparison, New York City has 1 restaurant for every 940 residents). The price range is huge, and you can spend anywhere from a small fortune to a couple bucks for every type of cuisine. Vegetarians and vegans will find SF a paradise, however contrary to popular belief the city has one of the lowest rates of vegetarian consumers in the nation. Sushi is a local obsession, and though you can find a sushi bar on almost every street corner, the Richmond district has more than its fair share of excellent sushi chefs.", 
				   entertainment: "There is an incredible array of events going on in San Francisco — virtually every day there will be something of interest to anyone going on, and San Francisco's mild climate ensures that practically every weekend will bring another major festival or some sort of large event.")
